<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>pdfdual.ico</ApplicationIcon>
    <AssemblyName>PDFDual</AssemblyName>
    <RootNamespace>PDFDual</RootNamespace>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="pdfdual.ico" />
    <Resource Include="pdfdual.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PdfSharp" Version="6.2.4" />
  </ItemGroup>

</Project>
