<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>iconcraft.ico</ApplicationIcon>
    <AssemblyName>IconCraft</AssemblyName>
    <RootNamespace>IconCraft</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="iconcraft.ico" />
    <Resource Include="iconcraft.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.116.1" />
    <PackageReference Include="Svg.Skia" Version="3.2.0" />
  </ItemGroup>

</Project>
